spring.datasource.url=jdbc:mysql://192.168.1.138:3306/reservas_db_test
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.refresh-token.expiration=604800000

stripe.api-key=${STRIPE_API_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.currency=EUR

spring.kafka.bootstrap-servers=192.168.1.138:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.group.user=user-group
kafka.group.loyalty=loyalty-group
kafka.group.email=email-group
kafka.group.payment=payment-group
kafka.group.notification=notifications-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
topics.booking-created=booking-created
topics.user-created=user-created

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=192.168.1.138
spring.data.redis.port=6379
spring.cache.type = redis
spring.cache.type.redis.time-to-live = 86400000


spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration