server {
    listen 80;
    server_name sistemareservas.com;

    location /api {
        proxy_pass http://backend-api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name test-sistemareservas.com;

    location /api {
        proxy_pass http://backend-api-test:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}