# Bloque http:

# $binary_remote_addr
# → Identifica al cliente por su IP (formato binario eficiente)

# zone
# → Reserva memoria compartida entre workers de Nginx
# → Guarda el estado del rate limiting

# rate
# → Define la tasa media de requests permitidas
# → No es un límite rígido, permite ráfagas controladas

http{
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=booking_hotel:10m rate=2r/s;
    limit_req_zone $binary_remote_addr zone=booking_flights:10m rate=2r/s;
}

# Bloque server

# burst
# → Permite picos temporales por encima del rate

#zone
# → Coge la referencia del bloque http y la aplica para ese conjunto de rutas

server{
    listen 80;
    server_name sistemareserva-test.com;

    location ~ ^/flights-reservation/.*/seats$ {
        limit_req zone=booking_flights burst=20 nodelay;
        proxy_pass http://backend-api-test:8080;
        proxy_set_header Host $host;
        proxy_set_header X-REAL-IP $remote_addr;
    }

    location ~ ^/hotels/.*/rooms/reservation$ {
        limit_req zone=booking_hotel burst=20 nodelay;
        proxy_pass http://backend-api-test:8080;
        proxy_set_header Host $host;
        proxy_set_header X-REAL-IP $remote_addr;
    }

    location /api {
        limit_req zone=api_limit burst=40 nodelay;
        proxy_pass http://backend-api-test:8080;
        proxy_set_header Host $host;
        proxy_set_header X-REAL-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}