server{
    listen 80;
    server_name sistemareserva.com;

    location /api {
        proxy_pass http://backend-api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-REAL-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}