services:
  backend-api-test:
    container_name: backend-api-test
    build: .
    image: asierhr/sistemareserva-test:v2.0   
    env_file:
      - ../.env    
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-reservas:3306/reservas_db_test
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_ACTIVE_PROFILE=testing
      - SPRING_DATA_REDIS_HOST=redis        
      - SPRING_DATA_REDIS_PORT=6379
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_HOST=${KAFKA_HOST}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_started }
      kafka: { condition: service_started }
    restart: on-failure
    networks:
      - sistema-reservas-net
networks:
  sistema-reservas-net:
    external: true
