name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests and Build Package
        run: mvn clean package
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY}}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
        
      - name: Build and push Docker Image
        uses: docker/build-push-action@v7.1.0
        with:
          context: .
          push: true
          tags: asierhr/sistemareserva-test:latest

  deploy:
    needs: build-test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          cd /home/asierhr/SistemaReserva/Docker-Compose-Local
          docker-compose -f docker-compose.yaml -f docker-compose-test.yaml pull
          ./initScript.sh
      
